// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWsovG4stK86Ryvl7DIo8VyuFYha8riCo',
    appId: '1:53586754054:web:4bab10264e6759546ba187',
    messagingSenderId: '53586754054',
    projectId: 'ziarat-app',
    authDomain: 'ziarat-app.firebaseapp.com',
    storageBucket: 'ziarat-app.firebasestorage.app',
    measurementId: 'G-SG2Z5H2X2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzWviACTGxpQYF12A8wlfDhXlNXZTLoW8',
    appId: '1:53586754054:android:bc03e09f8881d22e6ba187',
    messagingSenderId: '53586754054',
    projectId: 'ziarat-app',
    storageBucket: 'ziarat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_DGSREsyD1xsJI7PznpIiB5cdkxWfncY',
    appId: '1:53586754054:ios:4c71950da667d7836ba187',
    messagingSenderId: '53586754054',
    projectId: 'ziarat-app',
    storageBucket: 'ziarat-app.firebasestorage.app',
    iosBundleId: 'com.example.ziaratApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_DGSREsyD1xsJI7PznpIiB5cdkxWfncY',
    appId: '1:53586754054:ios:4c71950da667d7836ba187',
    messagingSenderId: '53586754054',
    projectId: 'ziarat-app',
    storageBucket: 'ziarat-app.firebasestorage.app',
    iosBundleId: 'com.example.ziaratApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWsovG4stK86Ryvl7DIo8VyuFYha8riCo',
    appId: '1:53586754054:web:3c6418fb91e6e3396ba187',
    messagingSenderId: '53586754054',
    projectId: 'ziarat-app',
    authDomain: 'ziarat-app.firebaseapp.com',
    storageBucket: 'ziarat-app.firebasestorage.app',
    measurementId: 'G-4M4BWK4LKQ',
  );
}
